### ISSUE TITLE
Paying Dues or Dues Command Prompts Survey

### ISSUE THREAD

**Issue by xar-tol** [RoboticsClubatUCF/MegaMan#30]
The dues command currently prompts with PayPal and has plans to flag members once paid. However, we have a survey that keeps track of members, which is manually sent to each member. It would be nice if this were automatic.

**Comment by VijayStroup** [comment]
This is what https://github.com/RoboticsClubatUCF/MegaMan/issues/6 hopes to accomplish.

The only thing bad about this approach is when someone does the dues command, some people may fill out the form without actually having paid the dues and thus, get the member role without paying anything.  A webhook from PayPal with the unique code identify the Discord user would automate this process of giving them the member role after they pay.  In this process, we can also send them a DM asking them to fill out the form.

**Comment by xar-tol** [comment]
#6 currently only sets out the accomplish the member role portion, not the survey. You can tack this onto it, but the survey needs to be added somehow.

**Comment by VijayStroup** [comment]
Will adjust #6 to fit this criteria.
