### ISSUE TITLE
Adding One-Off Lab Days

### ISSUE THREAD

**Issue by xar-tol** [RoboticsClubatUCF/MegaMan#31]
Currently there is a lab days command that alerts of some preset lab days.

Recently, we have had some one-off lab days pop up, and certain teams are more prone to having these sort of days. It would be nice if there could be a command for the "officer" role or the "team-lead" role to add a one-off day for the rest of the week to continue to automate finding when the lab is open.

Starting points: ex of this sort of addition being done before typically use some sort of variable for the item, which the command can replace, and a timer variable.

**Comment by VijayStroup** [comment]
Going to have to wait for a hosted database to implement this so we have persistence on redeployments.

**Comment by VijayStroup** [comment]
Solved with #45
